src/App.js, src/components/OrderItem.js, src/components/OrderList.js, src/components/OrderPopup.js, src/popup/OrderPopup.js, src/routes/Routing.js, src/styles/GlobalStyle.js
react routing 재구성
react routing 재구성 및 코드들 부분부분 수정(띄어쓰기 등)
src/routes/Routing.js
#12
=> feat: route

src/components/common/Header.js, src/components/order/OrderList.js, src/components/payment/PaymentList.js, src/components/payment/PaymentWay.js, src/popup/CardPopup.js, src/popup/CashPopup.js, src/popup/OrderPopup.js, src/popup/PaymentPopup.js
feat:PaymentPopup 개발
PaymentPopup.js
PaymentList.js
PaymentWay.js
#18
=> feat:PaymentPopup 개발

src/components/pos/PosCategory.js, src/components/pos/PosItem.js, src/pages/LoginPage.js, src/pages/PosPage.js
login 페이지 디자인 수정
login 페이지 디자인 수정
login 페이지 디자인 수정
#17
=> feat: login-design

src/popup/CardPopup.js
CardPopup 팝업 개발
CardPopup.js
#23
=> feat:CardPopup

src/pages/StorePage.js
UI/UX 개선
UI/UX 개선
UI/UX 개선
#27
=> feat: StorePage-design

src/pages/LoginPage.js, src/pages/SignupPage.js
UI/UX 개선 및 LoginPage 코드 수정
UI/UX 개선 및 LoginPage 코드 수정
UI/UX 개선 및 LoginPage 코드 수정
#25
=> feat: SignupPage

.eslintrc.js, src/popup/CashPopup.js
feat:CashPopup
CashPopup.js
#31
=> feat:CashPopup

src/components/order/OrderItem.js, src/components/order/OrderList.js, src/popup/IndexPopup.js, src/popup/OrderPopup.js
OrderPopup 기능추가
OrderPopup.js / OrderItem.js / OrderList 코드 수정
#33
=> feat/OrderPopup 기능추가

src/components/pos/PosCategory.js, src/components/pos/PosItem.js, src/pages/PosPage.js
PosPage 기초 기능 구현 완료
PosPage 기초 기능 구현 완료
PosPage 기초 기능 구현 완료
#16
=> feat: PosPage-design

src/components/payment/PaymentList.js, src/popup/PaymentPopup.js
feat/PaymentPopup OrderPopup연결
PaymentPopup 관련 파일
#18
=> feat/PaymentPopup OrderPopup연결

src/api/Orders/OrederItemsApi.js, src/components/order/OrderItem.js, src/components/payment/PaymentList.js, src/popup/CashPopup.js, src/popup/OrderPopup.js, src/recoil/atoms/ItemState.js
feat/CashPopup 결제금액 데이터 연동
CashPopup.js
#31
=> feat/CashPopup 결제금액 데이터 연동

src/api/Auth/StorePostApi.js, src/pages/SignupPage.js, src/pages/StorePage.js, src/recoil/atoms/StoreState.js
StorePage api 연동
StorePage api 연동
StorePage api 연동 완료
#47
=> feat: Storepage-api

src/api/auth/LoginPostApi.js, src/pages/LoginPage.js
LoginPage api 연동
LoginPage api 연동
LoginPage api 연동
#49
=> feat: LoginPage-api

src/api/Auth/StorePostApi.js, src/pages/LoginPage.js, src/pages/SignupPage.js, src/pages/StorePage.js
SignupPage, StorePage 유효성 세팅
SignupPage, StorePage 유효성 세팅
SignupPage, StorePage 유효성 세팅
#50
=> feat: StorePage-valid

src/api/Auth/SignupPostApi.js, src/api/Auth/StorePostApi.js, src/api/Auth/StoreTokenPostApi.js, src/pages/LoginPage.js, src/pages/PosPage.js, src/pages/SignupPage.js, src/pages/StorePage.js
LoginPage, SignupPage, StorePage api 및 유효성 완료
LoginPage, SignupPage, StorePage 추가 api통신 및 유효성 완료
SignupPage 아이디 중복확인
StorePage 넘어갈 때 Token 발급
#52
=> feat: Auth-valid

src/api/Items/ItemsApi.js, src/api/Orders/OrderGetTableApi.js, src/api/Orders/OrdersPutApi.js, src/api/pay/PayPutApi.js, src/api/pay/UnpaidGetApi.js, src/components/func/AtomData.js, src/components/order/OrderItem.js, src/components/order/OrderList.js, src/components/payment/PaymentList.js, src/components/payment/PaymentWay.js, src/pages/Home.js, src/popup/CashPopup.js, src/popup/OrderPopup.js, src/popup/PaymentPopup.js, src/recoil/atoms/ItemState.js
feat/TableSet table 별 주문조회 , api order 연동 , 결제방식
home.js / 모든 팝업
#33
=> feat/TableSet table 별 주문조회 , api order 연동 , 결제방식

src/App.js, src/api/pos/category/CategoryDeleteApi.js, src/api/pos/category/CategoryGetApi.js, src/api/pos/category/CategoryPostApi.js, src/api/pos/category/CategoryPutApi.js, src/api/pos/item/ItemDeleteApi.js, src/api/pos/item/ItemGetApi.js, src/api/pos/item/ItemPostApi.js, src/api/pos/item/ItemPutApi.js, src/components/pos/PosCategory.js, src/components/pos/PosItem.js, src/pages/PosPage.js, src/pages/SignupPage.js, src/pages/StorePage.js
PosPage 전체 구현 완료
PosPage api통신, 유효성검사, 예외처리 완료
#56
=> feat: PosPage-api

src/api/pay/PayPostApi.js, src/components/payment/PaymentWay.js, src/popup/CashPopup.js
feat/paymentApichange 결제api변경
payPutApi => PayPostApi
=> feat/paymentApichange 결제api변경

src/api/Items/ItemsApi.js, src/api/Orders/OrderGetTableApi.js, src/api/Orders/OrdersPostApi.js, src/api/Orders/OrdersPutApi.js, src/api/Token.js, src/api/pay/PayPostApi.js, src/api/pay/UnpaidGetApi.js, src/api/pos/category/CategoryDeleteApi.js, src/api/pos/category/CategoryGetApi.js, src/api/pos/category/CategoryPostApi.js, src/api/pos/category/CategoryPutApi.js, src/api/pos/item/ItemDeleteApi.js, src/api/pos/item/ItemGetApi.js, src/api/pos/item/ItemPostApi.js, src/api/pos/item/ItemPutApi.js
feat/apiSeparaion token 관련 모듈
feat/apiSeparaion token 관련 모듈
=> feat/apiSeparaion token 관련 모듈

src/api/Orders/OrdersPostApi.js, src/components/common/Header.js
feat/logout 로그아웃기능 구현
feat/logout 로그아웃기능 구현
=> feat/logout 로그아웃기능 구현

src/popup/CashPopup.js
feat/cashEdit 받은금액 >= 결제금액
feat/cashEdit 받은금액 >= 결제금액
=> feat/cashEdit 받은금액 >= 결제금액

src/pages/PosPage.js
=> feat: PosPage 디자인 수정

src/api/auth/info/InfoPostApi.js, src/api/auth/info/InfoPutApi.js, src/api/pos/category/CategoryDeleteApi.js, src/api/pos/category/CategoryGetApi.js, src/api/pos/category/CategoryPostApi.js, src/api/pos/category/CategoryPutApi.js, src/api/pos/item/ItemDeleteApi.js, src/api/pos/item/ItemGetApi.js, src/api/pos/item/ItemPostApi.js, src/api/pos/item/ItemPutApi.js, src/pages/InfoNpwPage.js, src/pages/InfoPage.js, src/recoil/atoms/InfoState.js, src/routes/Routing.js
기존 비밀번호 확인 및 비밀번호 변경 수정 완료
InfoPage, InfoNpwPage, InfoGetApi
#65
=> feat: InfoPage-add

src/components/order/OrderItem.js, src/components/payment/PaymentList.js, src/components/payment/PaymentWay.js, src/pages/Home.js, src/popup/CashPopup.js, src/popup/OrderPopup.js, src/popup/PaymentPopup.js
css/popup css 수정
css/popup css 수정'
#74
=> css/popup css 수정

src/components/order/OrderItem.js, src/components/pos/PosCategory.js, src/components/pos/PosItem.js, src/pages/Home.js, src/pages/InfoNpwPage.js, src/pages/InfoPage.js, src/pages/MyPage.js, src/pages/PosPage.js, src/popup/CardPopup.js, src/popup/OrderPopup.js
css/addPage css 수정완료
css/addPage css 수정완료
#75
=> css/addPage css 수정완료

src/components/common/Header.js, src/pages/KioskPage.js, src/recoil/atoms/KioskState.js, src/routes/Routing.js
feat/kiosk kiosk 기능 구현 완료
feat/kiosk kiosk 기능 구현 완료
=> feat/kiosk kiosk 기능 구현 완료

src/components/order/OrderItem.js, src/popup/CashPopup.js, src/popup/OrderPopup.js, src/popup/PaymentPopup.js, src/styles/CommonStyle.js
css/animation 팝업 / 사용자 관련
css/animation 팝업 / 사용자 관련
#80
=> css/animation 팝업 / 사용자 관련

src/components/common/Header.js, src/components/pos/PosItem.js, src/pages/InfoNpwPage.js, src/pages/LoginPage.js, src/routes/Routing.js
헤더의 키오스크 구현 후 routing error 해결
헤더의 키오스크 구현 후 routing error 해결
routing 재설정
키오스크 상태 조건 수정
#82
=> hotfix: routing-error

src/pages/LoginPage.js, src/pages/MyPage.js, src/styles/CommonStyle.js
=> css/animation 로그인 / 마이페이지 관련

package-lock.json, package.json, src/App.css, src/App.js, src/components/common/Footer.js, src/components/common/Header.js, src/components/order/OrderItem.js, src/components/pos/PosCategory.js, src/index.css, src/pages/LoginPage.js, src/pages/PosPage.js, src/pages/SignupPage.js, src/popup/CashPopup.js, src/popup/OrderPopup.js, src/popup/PaymentPopup.js, src/styles/CommonStyle.js
=> css/addedit 팀원 피드백 반영

src/App.css, src/pages/Home.js, src/styles/CommonStyle.js
=> css/animation 테이블 화면 관련

src/App.css, src/App.js, src/components/common/Footer.js, src/components/common/Header.js, src/index.css, src/pages/LoginPage.js, src/styles/CommonStyle.js
kiosk location change
kiosk location change
#90
=> kiosk location change

package-lock.json, src/api/cost/CostGetApi.js, src/api/cost/PriceGetApi.js, src/pages/CostPage.js, src/pages/KioskPage.js
에러 수정
hotfix: KioskPage css
KioskPage 애니메이션 수정
#96
=> hotfix: KioskPage css

src/App.css, src/components/common/Header.js, src/components/pos/PosCategory.js, src/components/pos/PosItem.js, src/index.css, src/pages/Home.js, src/pages/LoginPage.js, src/pages/MyPage.js, src/pages/PosPage.js, src/pages/SignupPage.js, src/pages/StorePage.js, src/styles/CommonStyle.js
팝업 제외 responsive
팝업 제외 responsive
#100
=> css/responsive 팝업 제외 responsive

src/pages/Home.js, src/popup/CardPopup.js, src/popup/CashPopup.js
=> css/animation 현금, 카드 결제 관련

src/api/BaseUrl.js, src/components/common/Header.js, src/components/order/OrderItem.js, src/components/order/OrderList.js, src/components/payment/PaymentList.js, src/components/payment/PaymentWay.js, src/components/pos/PosItem.js, src/pages/Home.js, src/pages/LoginPage.js, src/pages/MyPage.js, src/popup/CashPopup.js, src/popup/OrderPopup.js, src/popup/PaymentPopup.js, src/styles/CommonStyle.js
css/responsive 마이페이지관련제외 완
css/responsive 마이페이지관련제외 완
#100
=> css/responsive 마이페이지관련제외 완

src/pages/LoginPage.js, src/pages/MyPage.js
css/responsive/mypage & css/login 로고 추가
css/responsive/mypage & css/login 로고 추가
#90 #100
=> css/responsive/mypage & css/login 로고 추가

src/styles/CommonStyle.js
css/responsive common-title edit
css/responsive common-title edit
#100
=> css/responsive common-title edit

src/components/dashboard/MyCalendar.js, src/pages/CostPage.js, src/pages/DashboardPage.js
CostPage 부분변경 및 DashboardPage 컴포넌트 마크업
CostPage 부분변경 및 DashboardPage 컴포넌트 마크업
CostPage 부분변경 및 DashboardPage 컴포넌트 마크업
#117
=> feat: DashboardPage-next

src/components/common/Header.js, src/pages/KioskPage.js, src/pages/NotFoundPage.js, src/pages/WelcomePage.js, src/routes/Routing.js
404에러페이지에서 헤더 제거
Header.js 수정했습니다.
=> css/animation 404페이지 헤더 제거

src/App.js, src/components/common/Header.js, src/components/common/Layout.js, src/routes/Routing.js
=> css/animation 404에러페이지 관련

src/components/order/OrderItem.js
feat/kiosk 주문완료/ 주문취소 시 팝업 닫힘 x
feat/kiosk 주문완료/ 주문취소 시 팝업 닫힘 x
#79
=> feat/kiosk 주문완료/ 주문취소 시 팝업 닫힘 x

src/api/auth/signup/StorePostApi.js, src/components/common/Header.js, src/components/func/AtomData.js, src/pages/Home.js, src/pages/PosPage.js, src/pages/SignupPage.js, src/pages/StorePage.js, src/routes/PrivateRoute.js, src/routes/Routing.js
feat/route store-> pos 수정
feat/route store-> pos 수정
#
=> feat/route store-> pos 수정

src/api/pay/UnpaidGetApi.js, src/components/common/Header.js, src/components/pos/PosCategory.js, src/pages/PosPage.js, src/pages/StorePage.js, src/recoil/atoms/CategoryState.js, src/routes/PrivateRoute.js, src/routes/PublicRoute.js
hotfix/route 회원가입 -> pos 수정
hotfix/route 회원가입 -> pos 수정
#130
=> hotfix/route 회원가입 -> pos 수정

package-lock.json, package.json, src/api/dashboard/sales/LineGetApi.js, src/api/dashboard/sales/PieGetApi.js, src/components/dashboard/MyCalendar.css, src/components/dashboard/MyCalendar.js, src/pages/CostPage.js, src/pages/DashboardPage.js
대시보드 페이지 디자인 전까지 마무리
DashboardPage 확정 디자인 전까지 마무리
#136
=> feat: DashboardPage-fin

src/pages/LoginPage.js, src/pages/SignupPage.js, src/pages/StorePage.js, src/styles/CommonStyle.js
css/inputcss 경고메세지 수정
css/inputcss 경고메세지 수정
=> css/inputcss 경고메세지 수정

src/pages/InfoNpwPage.js, src/pages/InfoPage.js
css/inputcss 비밀번호 변경 페이지 추가 수정
css/inputcss 비밀번호 변경 페이지 추가 수정
=> css/inputcss 비밀번호 변경 페이지 추가 수정

src/api/dashboard/chart/LineGetApi.js, src/api/dashboard/chart/PieGetApi.js, src/api/dashboard/consulting/ConsultingGetApi.js, src/api/dashboard/consulting/ReqIdGetApi.js, src/api/dashboard/consulting/WaitGetApi.js, src/api/dashboard/consulting/test/ConsultingTestGetApi.js, src/api/dashboard/consulting/test/ReqIdTestGetApi.js, src/api/dashboard/consulting/test/WaitTestGetApi.js, src/components/dashboard/MyCalendar.js, src/pages/ConsultingPage.js, src/pages/DashboardPage.js, src/routes/Routing.js
api 연동 및 마크업 완료
ConsultingPage 마크업 및 api 연동
ConsultingPage 마크업
ConsultingPage api 연동
#140
=> feat: ConsultingPage-markup

src/api/dashboard/costs/CostsGetApi.js, src/api/dashboard/costs/CostsPostApi.js, src/pages/CostPage.js
feat/cost api 수정
feat/cost api 수정
=> feat/cost api 수정

src/components/common/Header.js, src/components/order/OrderItem.js, src/components/order/OrderList.js, src/components/payment/PaymentList.js, src/components/payment/PaymentWay.js, src/components/pos/PosCategory.js, src/components/pos/PosItem.js, src/pages/CostPage.js, src/pages/DashboardPage.js, src/popup/CardPopup.js, src/popup/CashPopup.js, src/popup/OrderPopup.js, src/popup/PaymentPopup.js, src/styles/CommonStyle.js
커서 포인터 등록 및 텍스트 커서 제거
커서 포인터 등록 및 텍스트 커서 제거
커서 포인터 등록
텍스트 커서 제거
#152
=> css: cursor-pointer

src/pages/PosPage.js
카테고리 데이터 있을 시 최초 렌더링 때 맨 처음 카테고리 선택된 상태
카테고리 데이터 있을 시 최초 렌더링 때 맨 처음 카테고리 선택된 상태
카테고리 데이터 있을 시 최초 렌더링 때 맨 처음 카테고리 선택된 상태
#156
=> feat: PosPage-cate

src/components/dashboard/MyCalendar.js, src/pages/DashboardPage.js
=> feat: Calendar-css

src/popup/CardPopup.js
=> spinner edit

README.md, src/components/dashboard/MyChart.jsx, src/components/pos/PosCategory.jsx, src/components/pos/PosItem.jsx, src/pages/ConsultingPage.jsx, src/pages/DashboardPage.jsx, src/pages/PosPage.jsx
Pos, Dashboard, Consulting 코드 버그 수정 및 리드미 추가
Pos, Dashboard, Consulting 코드 버그 수정 및 리드미 추가
Pos, Dashboard, Consulting 코드 버그 수정
리드미 추가
#170
=> hotfix: Code-refactoring
